version: "2"

services:
  urlshortener:
    container_name: urlshortener
    build: ./urlshortener
    expose: 
      - 8080
    environment:
      - HOSTNAME=localhost
      - PORT=8000
    volumes:
      - ./urlshortener:/usr/src/app
    networks:
      - backbone
    command: /usr/local/bin/gunicorn -c gunicorn.py main:api

  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - backbone
    ports:
      - "8000:8000"

networks:
  backbone:
    driver: bridge